jobs:
  build:
    name: Java ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      run: java -version && mvn --version
    - continue-on-error: true
      run: mvn --activate-profiles dist --no-transfer-progress package
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8
        - 11
        - 17
        - 21
name: Maven Build
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
